name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unix-builds:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build all for Unix
      run: cargo build --verbose
    - name: Build reverse shell for Unix
      run: cargo build -p tcp_reverse_shell --verbose
    - name: Build process migration for Unix
      run: cargo build -p process_migration --verbose
      
  windows-builds:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install linker
      run: sudo apt -y install mingw-w64
    - name: Add Windows build target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build all for Windows
      run: cargo build --target x86_64-pc-windows-gnu --verbose
    - name: Build reverse shell for Windows
      run: cargo build -p tcp_reverse_shell --target x86_64-pc-windows-gnu --verbose
    - name: Build process migration for Windows
      run: cargo build -p process_migration --target x86_64-pc-windows-gnu --verbose
